<ElectricityScreen>:
    BoxLayout:
        MDTopAppBar:
            id: top_bar
            title: "Электричество"
            pos_hint: {"center_x": 0.5, "center_y": 0.97}
            left_action_items: [["arrow-left-bold-circle-outline", lambda x: root.go_back()]]
            right_action_items: [["account", lambda x: root.open_account()]]
            elevation: 1
            md_bg_color: 168/255, 228/255, 160/255, 1
